table 'Project Management Data'
	lineageTag: 26504825-ee35-4227-8178-def425658dce

	column 'Excel Sample Data'
		dataType: string
		lineageTag: 952785da-590b-4a7c-86f0-19a1dce0ccda
		summarizeBy: none
		sourceColumn: Excel Sample Data

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 02f907b3-19c8-4907-a5f8-f8f3674107f0
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: ba865ee0-ee64-4e26-909d-6871e49bf005
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 84a5327c-01f6-495d-9735-ce64a2ea9730
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: c48be0bf-075a-4a75-8abd-afddacd896fe
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 88d2940c-aedd-4a3d-a8a9-ec6690ee164a
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 0179781d-f39d-4ec7-8a43-6d3a2d6ab31c
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	partition 'Project Management Data' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Administrator\Downloads\Project-Management-Sample-Data.xlsx"), null, true),
				    #"Project Management Data_Sheet" = Source{[Item="Project Management Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Project Management Data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Excel Sample Data", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

