table 'Project Management Data'
	lineageTag: e4617201-a058-46cd-84cc-53cc05be686a

	column 'Excel Sample Data'
		dataType: string
		lineageTag: 66d00a54-b626-4119-84a7-d616a0a782d5
		summarizeBy: none
		sourceColumn: Excel Sample Data

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 5821f614-76c1-4cd9-86ee-28c044732caa
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: b72d37d9-44a2-430a-b0a8-364584f61497
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: c3f6dd64-1f72-471b-a943-50b816ad2422
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: b42bdbaf-02e6-4ef0-9f72-5fe3232ea5a5
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 3e3ff186-df35-4ae0-9c87-523dfda62811
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 87b61c5c-c31c-45c9-b845-bad6fcf61bb1
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	partition 'Project Management Data' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Administrator\Downloads\Project-Management-Sample-Data.xlsx"), null, true),
				    #"Project Management Data_Sheet" = Source{[Item="Project Management Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Project Management Data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Excel Sample Data", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

