table Order_Subtotals
	lineageTag: 39af82bb-b9e4-4ee4-a155-52279a329a75

	measure TotalMeasure =
			CALCULATE(SUM(Order_Subtotals[Subtotal])
			)
		lineageTag: 06824801-9d48-4edb-bf57-05662ec8ccdf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 5c2a172f-5fbf-4065-a8b3-4900b5906b12
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column Subtotal
		dataType: double
		lineageTag: 79cc2373-f14a-40e8-a01d-1ad655f0e95e
		summarizeBy: none
		sourceColumn: Subtotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Order_Subtotals = m
		mode: import
		source =
				let
				    Source = OData.Feed("https://services.odata.org/V3/Northwind/Northwind.svc/", null, [Implementation="2.0"]),
				    Order_Subtotals_table = Source{[Name="Order_Subtotals",Signature="table"]}[Data],
				    FirstTenRows = Table.FirstN(Order_Subtotals_table, 10)
				in
				    FirstTenRows

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

