table financials
	lineageTag: 6b8d73ca-bbc9-4da5-9183-dbee3726165b

	column Segment
		dataType: string
		lineageTag: 9e700836-f4b7-4501-be58-6e6f682685aa
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a0752a8f-f3a3-4613-b203-a7cf78bf32b7
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: a174007b-d0d4-440b-a5c9-4649ab15bd1b
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: bea5bf80-7059-44bd-9bb4-ed7c8a47f082
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: c84a0938-385d-4d64-b22a-9b26bff40550
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: 73d54066-9bc7-46b9-a810-bc1673b00311
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 604d1fdb-50c9-4555-aeda-eff5fb7592b9
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: f642dd22-956a-47b8-b28e-03e9b61e952f
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: 6cd710a4-eb85-42bb-8bb7-16e1861b97a9
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ' Sales'
		dataType: double
		lineageTag: c0848270-dcb2-4bd4-980f-d0d1c97df68e
		summarizeBy: sum
		sourceColumn: " Sales"

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: 41fa9dd5-b683-42f9-820f-8e71f055df09
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: d984070e-ef02-48ed-b92e-bab686926834
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8ee5b201-dabd-4215-8d22-7566ec5ff071
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 3e69f0a5-6ef2-496a-aff4-f1469637338d
			defaultHierarchy: LocalDateTable_eda564e0-9a4c-4465-ba7b-c19a90712910.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: fec4dfae-41b6-4869-b39f-26110e4d84e0
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 669998bf-50dc-4fa2-b0ee-bdb6ded711b5
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3502dd90-92a5-4e19-8b0f-498a4f4b5cd3
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Date - Copy'
		dataType: dateTime
		formatString: General Date
		lineageTag: a8c7bf0e-6684-410a-b602-8f5523098a65
		summarizeBy: none
		sourceColumn: Date - Copy

		variation Variation
			isDefault
			relationship: 4fdb6b19-703f-44ea-86de-c09f3e903ce5
			defaultHierarchy: LocalDateTable_f13a4efa-3ae0-4f17-a7a6-473817a55962.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\Microsoft Power BI Desktop\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {" Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Date", "Date - Copy"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Column",{"Segment", "Country", "Product", "Discount Band", "Units Sold", "Manufacturing Price", "Sale Price", "Gross Sales", "Discounts", " Sales", "COGS", "Profit", "Month Number", "Year", "Month Name", "Date", "Date - Copy"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns",{{"Date - Copy", type datetime}})
				in
				 #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

